project:
  type: website
  output-dir: docs

website:
  title: "Shermaine's Webpage"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: DataVisualization.qmd
        text: Data Visualization
      - href: Hobbies.qmd
        text: Hobbies
      - href: Reflection.qmd
        text: Reflection
      - href: MyProject.qmd
        text: MyProject

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



